// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rest/tenancy/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/rest/tenancy/client.go -destination=pkg/rest/tenancy/mock_client.go -package=tenancy
//

// Package tenancy is a generated GoMock package.
package tenancy

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// DELETEV1OrgsOrgOrg mocks base method.
func (m *MockClientInterface) DELETEV1OrgsOrgOrg(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1OrgsOrgOrg", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1OrgsOrgOrg indicates an expected call of DELETEV1OrgsOrgOrg.
func (mr *MockClientInterfaceMockRecorder) DELETEV1OrgsOrgOrg(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1OrgsOrgOrg", reflect.TypeOf((*MockClientInterface)(nil).DELETEV1OrgsOrgOrg), varargs...)
}

// DELETEV1ProjectsProjectProject mocks base method.
func (m *MockClientInterface) DELETEV1ProjectsProjectProject(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1ProjectsProjectProject", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1ProjectsProjectProject indicates an expected call of DELETEV1ProjectsProjectProject.
func (mr *MockClientInterfaceMockRecorder) DELETEV1ProjectsProjectProject(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1ProjectsProjectProject", reflect.TypeOf((*MockClientInterface)(nil).DELETEV1ProjectsProjectProject), varargs...)
}

// DELETEV1ProjectsProjectProjectNetworksNetworkNetwork mocks base method.
func (m *MockClientInterface) DELETEV1ProjectsProjectProjectNetworksNetworkNetwork(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1ProjectsProjectProjectNetworksNetworkNetwork", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1ProjectsProjectProjectNetworksNetworkNetwork indicates an expected call of DELETEV1ProjectsProjectProjectNetworksNetworkNetwork.
func (mr *MockClientInterfaceMockRecorder) DELETEV1ProjectsProjectProjectNetworksNetworkNetwork(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1ProjectsProjectProjectNetworksNetworkNetwork", reflect.TypeOf((*MockClientInterface)(nil).DELETEV1ProjectsProjectProjectNetworksNetworkNetwork), varargs...)
}

// GETV1OrgsOrgOrg mocks base method.
func (m *MockClientInterface) GETV1OrgsOrgOrg(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrg", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrg indicates an expected call of GETV1OrgsOrgOrg.
func (mr *MockClientInterfaceMockRecorder) GETV1OrgsOrgOrg(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrg", reflect.TypeOf((*MockClientInterface)(nil).GETV1OrgsOrgOrg), varargs...)
}

// GETV1OrgsOrgOrgFolders mocks base method.
func (m *MockClientInterface) GETV1OrgsOrgOrgFolders(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrgFolders", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrgFolders indicates an expected call of GETV1OrgsOrgOrgFolders.
func (mr *MockClientInterfaceMockRecorder) GETV1OrgsOrgOrgFolders(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrgFolders", reflect.TypeOf((*MockClientInterface)(nil).GETV1OrgsOrgOrgFolders), varargs...)
}

// GETV1OrgsOrgOrgStatus mocks base method.
func (m *MockClientInterface) GETV1OrgsOrgOrgStatus(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrgStatus", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrgStatus indicates an expected call of GETV1OrgsOrgOrgStatus.
func (mr *MockClientInterfaceMockRecorder) GETV1OrgsOrgOrgStatus(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrgStatus", reflect.TypeOf((*MockClientInterface)(nil).GETV1OrgsOrgOrgStatus), varargs...)
}

// GETV1ProjectsProjectProject mocks base method.
func (m *MockClientInterface) GETV1ProjectsProjectProject(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProject", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProject indicates an expected call of GETV1ProjectsProjectProject.
func (mr *MockClientInterfaceMockRecorder) GETV1ProjectsProjectProject(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProject", reflect.TypeOf((*MockClientInterface)(nil).GETV1ProjectsProjectProject), varargs...)
}

// GETV1ProjectsProjectProjectNetworks mocks base method.
func (m *MockClientInterface) GETV1ProjectsProjectProjectNetworks(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworks", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworks indicates an expected call of GETV1ProjectsProjectProjectNetworks.
func (mr *MockClientInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworks(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworks", reflect.TypeOf((*MockClientInterface)(nil).GETV1ProjectsProjectProjectNetworks), varargs...)
}

// GETV1ProjectsProjectProjectNetworksNetworkNetwork mocks base method.
func (m *MockClientInterface) GETV1ProjectsProjectProjectNetworksNetworkNetwork(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworksNetworkNetwork", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworksNetworkNetwork indicates an expected call of GETV1ProjectsProjectProjectNetworksNetworkNetwork.
func (mr *MockClientInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworksNetworkNetwork(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworksNetworkNetwork", reflect.TypeOf((*MockClientInterface)(nil).GETV1ProjectsProjectProjectNetworksNetworkNetwork), varargs...)
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus mocks base method.
func (m *MockClientInterface) GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus indicates an expected call of GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus.
func (mr *MockClientInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus", reflect.TypeOf((*MockClientInterface)(nil).GETV1ProjectsProjectProjectNetworksNetworkNetworkStatus), varargs...)
}

// GETV1ProjectsProjectProjectStatus mocks base method.
func (m *MockClientInterface) GETV1ProjectsProjectProjectStatus(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectStatus", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectStatus indicates an expected call of GETV1ProjectsProjectProjectStatus.
func (mr *MockClientInterfaceMockRecorder) GETV1ProjectsProjectProjectStatus(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectStatus", reflect.TypeOf((*MockClientInterface)(nil).GETV1ProjectsProjectProjectStatus), varargs...)
}

// LISTV1Orgs mocks base method.
func (m *MockClientInterface) LISTV1Orgs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1Orgs", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1Orgs indicates an expected call of LISTV1Orgs.
func (mr *MockClientInterfaceMockRecorder) LISTV1Orgs(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1Orgs", reflect.TypeOf((*MockClientInterface)(nil).LISTV1Orgs), varargs...)
}

// LISTV1Projects mocks base method.
func (m *MockClientInterface) LISTV1Projects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1Projects", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1Projects indicates an expected call of LISTV1Projects.
func (mr *MockClientInterfaceMockRecorder) LISTV1Projects(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1Projects", reflect.TypeOf((*MockClientInterface)(nil).LISTV1Projects), varargs...)
}

// LISTV1ProjectsProjectProjectNetworks mocks base method.
func (m *MockClientInterface) LISTV1ProjectsProjectProjectNetworks(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1ProjectsProjectProjectNetworks", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1ProjectsProjectProjectNetworks indicates an expected call of LISTV1ProjectsProjectProjectNetworks.
func (mr *MockClientInterfaceMockRecorder) LISTV1ProjectsProjectProjectNetworks(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1ProjectsProjectProjectNetworks", reflect.TypeOf((*MockClientInterface)(nil).LISTV1ProjectsProjectProjectNetworks), varargs...)
}

// PUTV1OrgsOrgOrg mocks base method.
func (m *MockClientInterface) PUTV1OrgsOrgOrg(ctx context.Context, orgOrg string, params *PUTV1OrgsOrgOrgParams, body PUTV1OrgsOrgOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1OrgsOrgOrg", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1OrgsOrgOrg indicates an expected call of PUTV1OrgsOrgOrg.
func (mr *MockClientInterfaceMockRecorder) PUTV1OrgsOrgOrg(ctx, orgOrg, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1OrgsOrgOrg", reflect.TypeOf((*MockClientInterface)(nil).PUTV1OrgsOrgOrg), varargs...)
}

// PUTV1OrgsOrgOrgWithBody mocks base method.
func (m *MockClientInterface) PUTV1OrgsOrgOrgWithBody(ctx context.Context, orgOrg string, params *PUTV1OrgsOrgOrgParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1OrgsOrgOrgWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1OrgsOrgOrgWithBody indicates an expected call of PUTV1OrgsOrgOrgWithBody.
func (mr *MockClientInterfaceMockRecorder) PUTV1OrgsOrgOrgWithBody(ctx, orgOrg, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1OrgsOrgOrgWithBody", reflect.TypeOf((*MockClientInterface)(nil).PUTV1OrgsOrgOrgWithBody), varargs...)
}

// PUTV1ProjectsProjectProject mocks base method.
func (m *MockClientInterface) PUTV1ProjectsProjectProject(ctx context.Context, projectProject string, params *PUTV1ProjectsProjectProjectParams, body PUTV1ProjectsProjectProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProject", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProject indicates an expected call of PUTV1ProjectsProjectProject.
func (mr *MockClientInterfaceMockRecorder) PUTV1ProjectsProjectProject(ctx, projectProject, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProject", reflect.TypeOf((*MockClientInterface)(nil).PUTV1ProjectsProjectProject), varargs...)
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetwork mocks base method.
func (m *MockClientInterface) PUTV1ProjectsProjectProjectNetworksNetworkNetwork(ctx context.Context, projectProject, networkNetwork string, params *PUTV1ProjectsProjectProjectNetworksNetworkNetworkParams, body PUTV1ProjectsProjectProjectNetworksNetworkNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectNetworksNetworkNetwork", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetwork indicates an expected call of PUTV1ProjectsProjectProjectNetworksNetworkNetwork.
func (mr *MockClientInterfaceMockRecorder) PUTV1ProjectsProjectProjectNetworksNetworkNetwork(ctx, projectProject, networkNetwork, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectNetworksNetworkNetwork", reflect.TypeOf((*MockClientInterface)(nil).PUTV1ProjectsProjectProjectNetworksNetworkNetwork), varargs...)
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody mocks base method.
func (m *MockClientInterface) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody(ctx context.Context, projectProject, networkNetwork string, params *PUTV1ProjectsProjectProjectNetworksNetworkNetworkParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody indicates an expected call of PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody.
func (mr *MockClientInterfaceMockRecorder) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody(ctx, projectProject, networkNetwork, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody", reflect.TypeOf((*MockClientInterface)(nil).PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBody), varargs...)
}

// PUTV1ProjectsProjectProjectWithBody mocks base method.
func (m *MockClientInterface) PUTV1ProjectsProjectProjectWithBody(ctx context.Context, projectProject string, params *PUTV1ProjectsProjectProjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectWithBody indicates an expected call of PUTV1ProjectsProjectProjectWithBody.
func (mr *MockClientInterfaceMockRecorder) PUTV1ProjectsProjectProjectWithBody(ctx, projectProject, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectWithBody", reflect.TypeOf((*MockClientInterface)(nil).PUTV1ProjectsProjectProjectWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// DELETEV1OrgsOrgOrgWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DELETEV1OrgsOrgOrgWithResponse(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*DELETEV1OrgsOrgOrgResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1OrgsOrgOrgWithResponse", varargs...)
	ret0, _ := ret[0].(*DELETEV1OrgsOrgOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1OrgsOrgOrgWithResponse indicates an expected call of DELETEV1OrgsOrgOrgWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DELETEV1OrgsOrgOrgWithResponse(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1OrgsOrgOrgWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DELETEV1OrgsOrgOrgWithResponse), varargs...)
}

// DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*DELETEV1ProjectsProjectProjectNetworksNetworkNetworkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", varargs...)
	ret0, _ := ret[0].(*DELETEV1ProjectsProjectProjectNetworksNetworkNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse indicates an expected call of DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DELETEV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse), varargs...)
}

// DELETEV1ProjectsProjectProjectWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DELETEV1ProjectsProjectProjectWithResponse(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*DELETEV1ProjectsProjectProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DELETEV1ProjectsProjectProjectWithResponse", varargs...)
	ret0, _ := ret[0].(*DELETEV1ProjectsProjectProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DELETEV1ProjectsProjectProjectWithResponse indicates an expected call of DELETEV1ProjectsProjectProjectWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DELETEV1ProjectsProjectProjectWithResponse(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETEV1ProjectsProjectProjectWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).DELETEV1ProjectsProjectProjectWithResponse), varargs...)
}

// GETV1OrgsOrgOrgFoldersWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1OrgsOrgOrgFoldersWithResponse(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*GETV1OrgsOrgOrgFoldersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrgFoldersWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1OrgsOrgOrgFoldersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrgFoldersWithResponse indicates an expected call of GETV1OrgsOrgOrgFoldersWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1OrgsOrgOrgFoldersWithResponse(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrgFoldersWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1OrgsOrgOrgFoldersWithResponse), varargs...)
}

// GETV1OrgsOrgOrgStatusWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1OrgsOrgOrgStatusWithResponse(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*GETV1OrgsOrgOrgStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrgStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1OrgsOrgOrgStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrgStatusWithResponse indicates an expected call of GETV1OrgsOrgOrgStatusWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1OrgsOrgOrgStatusWithResponse(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrgStatusWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1OrgsOrgOrgStatusWithResponse), varargs...)
}

// GETV1OrgsOrgOrgWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1OrgsOrgOrgWithResponse(ctx context.Context, orgOrg string, reqEditors ...RequestEditorFn) (*GETV1OrgsOrgOrgResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1OrgsOrgOrgWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1OrgsOrgOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1OrgsOrgOrgWithResponse indicates an expected call of GETV1OrgsOrgOrgWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1OrgsOrgOrgWithResponse(ctx, orgOrg any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1OrgsOrgOrgWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1OrgsOrgOrgWithResponse), varargs...)
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse indicates an expected call of GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1ProjectsProjectProjectNetworksNetworkNetworkStatusWithResponse), varargs...)
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx context.Context, projectProject, networkNetwork string, reqEditors ...RequestEditorFn) (*GETV1ProjectsProjectProjectNetworksNetworkNetworkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1ProjectsProjectProjectNetworksNetworkNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse indicates an expected call of GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx, projectProject, networkNetwork any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse), varargs...)
}

// GETV1ProjectsProjectProjectNetworksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1ProjectsProjectProjectNetworksWithResponse(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*GETV1ProjectsProjectProjectNetworksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectNetworksWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1ProjectsProjectProjectNetworksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectNetworksWithResponse indicates an expected call of GETV1ProjectsProjectProjectNetworksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1ProjectsProjectProjectNetworksWithResponse(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectNetworksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1ProjectsProjectProjectNetworksWithResponse), varargs...)
}

// GETV1ProjectsProjectProjectStatusWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1ProjectsProjectProjectStatusWithResponse(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*GETV1ProjectsProjectProjectStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1ProjectsProjectProjectStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectStatusWithResponse indicates an expected call of GETV1ProjectsProjectProjectStatusWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1ProjectsProjectProjectStatusWithResponse(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectStatusWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1ProjectsProjectProjectStatusWithResponse), varargs...)
}

// GETV1ProjectsProjectProjectWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GETV1ProjectsProjectProjectWithResponse(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*GETV1ProjectsProjectProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GETV1ProjectsProjectProjectWithResponse", varargs...)
	ret0, _ := ret[0].(*GETV1ProjectsProjectProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GETV1ProjectsProjectProjectWithResponse indicates an expected call of GETV1ProjectsProjectProjectWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GETV1ProjectsProjectProjectWithResponse(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GETV1ProjectsProjectProjectWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GETV1ProjectsProjectProjectWithResponse), varargs...)
}

// LISTV1OrgsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) LISTV1OrgsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LISTV1OrgsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1OrgsWithResponse", varargs...)
	ret0, _ := ret[0].(*LISTV1OrgsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1OrgsWithResponse indicates an expected call of LISTV1OrgsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) LISTV1OrgsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1OrgsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).LISTV1OrgsWithResponse), varargs...)
}

// LISTV1ProjectsProjectProjectNetworksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) LISTV1ProjectsProjectProjectNetworksWithResponse(ctx context.Context, projectProject string, reqEditors ...RequestEditorFn) (*LISTV1ProjectsProjectProjectNetworksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1ProjectsProjectProjectNetworksWithResponse", varargs...)
	ret0, _ := ret[0].(*LISTV1ProjectsProjectProjectNetworksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1ProjectsProjectProjectNetworksWithResponse indicates an expected call of LISTV1ProjectsProjectProjectNetworksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) LISTV1ProjectsProjectProjectNetworksWithResponse(ctx, projectProject any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1ProjectsProjectProjectNetworksWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).LISTV1ProjectsProjectProjectNetworksWithResponse), varargs...)
}

// LISTV1ProjectsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) LISTV1ProjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LISTV1ProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LISTV1ProjectsWithResponse", varargs...)
	ret0, _ := ret[0].(*LISTV1ProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LISTV1ProjectsWithResponse indicates an expected call of LISTV1ProjectsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) LISTV1ProjectsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LISTV1ProjectsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).LISTV1ProjectsWithResponse), varargs...)
}

// PUTV1OrgsOrgOrgWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1OrgsOrgOrgWithBodyWithResponse(ctx context.Context, orgOrg string, params *PUTV1OrgsOrgOrgParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PUTV1OrgsOrgOrgResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1OrgsOrgOrgWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1OrgsOrgOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1OrgsOrgOrgWithBodyWithResponse indicates an expected call of PUTV1OrgsOrgOrgWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1OrgsOrgOrgWithBodyWithResponse(ctx, orgOrg, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1OrgsOrgOrgWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1OrgsOrgOrgWithBodyWithResponse), varargs...)
}

// PUTV1OrgsOrgOrgWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1OrgsOrgOrgWithResponse(ctx context.Context, orgOrg string, params *PUTV1OrgsOrgOrgParams, body PUTV1OrgsOrgOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*PUTV1OrgsOrgOrgResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orgOrg, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1OrgsOrgOrgWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1OrgsOrgOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1OrgsOrgOrgWithResponse indicates an expected call of PUTV1OrgsOrgOrgWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1OrgsOrgOrgWithResponse(ctx, orgOrg, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orgOrg, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1OrgsOrgOrgWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1OrgsOrgOrgWithResponse), varargs...)
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse(ctx context.Context, projectProject, networkNetwork string, params *PUTV1ProjectsProjectProjectNetworksNetworkNetworkParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PUTV1ProjectsProjectProjectNetworksNetworkNetworkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1ProjectsProjectProjectNetworksNetworkNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse indicates an expected call of PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse(ctx, projectProject, networkNetwork, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithBodyWithResponse), varargs...)
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx context.Context, projectProject, networkNetwork string, params *PUTV1ProjectsProjectProjectNetworksNetworkNetworkParams, body PUTV1ProjectsProjectProjectNetworksNetworkNetworkJSONRequestBody, reqEditors ...RequestEditorFn) (*PUTV1ProjectsProjectProjectNetworksNetworkNetworkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, networkNetwork, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1ProjectsProjectProjectNetworksNetworkNetworkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse indicates an expected call of PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse(ctx, projectProject, networkNetwork, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, networkNetwork, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1ProjectsProjectProjectNetworksNetworkNetworkWithResponse), varargs...)
}

// PUTV1ProjectsProjectProjectWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1ProjectsProjectProjectWithBodyWithResponse(ctx context.Context, projectProject string, params *PUTV1ProjectsProjectProjectParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PUTV1ProjectsProjectProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1ProjectsProjectProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectWithBodyWithResponse indicates an expected call of PUTV1ProjectsProjectProjectWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1ProjectsProjectProjectWithBodyWithResponse(ctx, projectProject, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1ProjectsProjectProjectWithBodyWithResponse), varargs...)
}

// PUTV1ProjectsProjectProjectWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PUTV1ProjectsProjectProjectWithResponse(ctx context.Context, projectProject string, params *PUTV1ProjectsProjectProjectParams, body PUTV1ProjectsProjectProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*PUTV1ProjectsProjectProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectProject, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PUTV1ProjectsProjectProjectWithResponse", varargs...)
	ret0, _ := ret[0].(*PUTV1ProjectsProjectProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PUTV1ProjectsProjectProjectWithResponse indicates an expected call of PUTV1ProjectsProjectProjectWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PUTV1ProjectsProjectProjectWithResponse(ctx, projectProject, params, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectProject, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUTV1ProjectsProjectProjectWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PUTV1ProjectsProjectProjectWithResponse), varargs...)
}
