// Package mps provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package mps

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1ProjectsProjectNameDmAmtGeneralSettingsGuid request
	GetV1ProjectsProjectNameDmAmtGeneralSettingsGuid(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1ProjectsProjectNameDmDevicesGuid request
	DeleteV1ProjectsProjectNameDmDevicesGuid(ctx context.Context, projectName string, guid string, params *DeleteV1ProjectsProjectNameDmDevicesGuidParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ProjectsProjectNameDmDevicesGuid request
	GetV1ProjectsProjectNameDmDevicesGuid(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1ProjectsProjectNameDmAmtGeneralSettingsGuid(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidRequest(c.Server, projectName, guid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1ProjectsProjectNameDmDevicesGuid(ctx context.Context, projectName string, guid string, params *DeleteV1ProjectsProjectNameDmDevicesGuidParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1ProjectsProjectNameDmDevicesGuidRequest(c.Server, projectName, guid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ProjectsProjectNameDmDevicesGuid(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ProjectsProjectNameDmDevicesGuidRequest(c.Server, projectName, guid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidRequest generates requests for GetV1ProjectsProjectNameDmAmtGeneralSettingsGuid
func NewGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidRequest(server string, projectName string, guid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectName", runtime.ParamLocationPath, projectName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "guid", runtime.ParamLocationPath, guid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/%s/dm/amt/generalSettings/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteV1ProjectsProjectNameDmDevicesGuidRequest generates requests for DeleteV1ProjectsProjectNameDmDevicesGuid
func NewDeleteV1ProjectsProjectNameDmDevicesGuidRequest(server string, projectName string, guid string, params *DeleteV1ProjectsProjectNameDmDevicesGuidParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectName", runtime.ParamLocationPath, projectName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "guid", runtime.ParamLocationPath, guid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/%s/dm/devices/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.IsSecretToBeDeleted != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "isSecretToBeDeleted", runtime.ParamLocationQuery, *params.IsSecretToBeDeleted); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ProjectsProjectNameDmDevicesGuidRequest generates requests for GetV1ProjectsProjectNameDmDevicesGuid
func NewGetV1ProjectsProjectNameDmDevicesGuidRequest(server string, projectName string, guid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectName", runtime.ParamLocationPath, projectName)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "guid", runtime.ParamLocationPath, guid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/%s/dm/devices/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidWithResponse request
	GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidWithResponse(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse, error)

	// DeleteV1ProjectsProjectNameDmDevicesGuidWithResponse request
	DeleteV1ProjectsProjectNameDmDevicesGuidWithResponse(ctx context.Context, projectName string, guid string, params *DeleteV1ProjectsProjectNameDmDevicesGuidParams, reqEditors ...RequestEditorFn) (*DeleteV1ProjectsProjectNameDmDevicesGuidResponse, error)

	// GetV1ProjectsProjectNameDmDevicesGuidWithResponse request
	GetV1ProjectsProjectNameDmDevicesGuidWithResponse(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*GetV1ProjectsProjectNameDmDevicesGuidResponse, error)
}

type GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GeneralSettingsResponse
}

// Status returns HTTPResponse.Status
func (r GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1ProjectsProjectNameDmDevicesGuidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON204      *DeleteResponse
	JSON404      *DeleteErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteV1ProjectsProjectNameDmDevicesGuidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1ProjectsProjectNameDmDevicesGuidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ProjectsProjectNameDmDevicesGuidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Device
}

// Status returns HTTPResponse.Status
func (r GetV1ProjectsProjectNameDmDevicesGuidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ProjectsProjectNameDmDevicesGuidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidWithResponse request returning *GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse
func (c *ClientWithResponses) GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidWithResponse(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse, error) {
	rsp, err := c.GetV1ProjectsProjectNameDmAmtGeneralSettingsGuid(ctx, projectName, guid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse(rsp)
}

// DeleteV1ProjectsProjectNameDmDevicesGuidWithResponse request returning *DeleteV1ProjectsProjectNameDmDevicesGuidResponse
func (c *ClientWithResponses) DeleteV1ProjectsProjectNameDmDevicesGuidWithResponse(ctx context.Context, projectName string, guid string, params *DeleteV1ProjectsProjectNameDmDevicesGuidParams, reqEditors ...RequestEditorFn) (*DeleteV1ProjectsProjectNameDmDevicesGuidResponse, error) {
	rsp, err := c.DeleteV1ProjectsProjectNameDmDevicesGuid(ctx, projectName, guid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1ProjectsProjectNameDmDevicesGuidResponse(rsp)
}

// GetV1ProjectsProjectNameDmDevicesGuidWithResponse request returning *GetV1ProjectsProjectNameDmDevicesGuidResponse
func (c *ClientWithResponses) GetV1ProjectsProjectNameDmDevicesGuidWithResponse(ctx context.Context, projectName string, guid string, reqEditors ...RequestEditorFn) (*GetV1ProjectsProjectNameDmDevicesGuidResponse, error) {
	rsp, err := c.GetV1ProjectsProjectNameDmDevicesGuid(ctx, projectName, guid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ProjectsProjectNameDmDevicesGuidResponse(rsp)
}

// ParseGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse parses an HTTP response from a GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidWithResponse call
func ParseGetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse(rsp *http.Response) (*GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ProjectsProjectNameDmAmtGeneralSettingsGuidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GeneralSettingsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteV1ProjectsProjectNameDmDevicesGuidResponse parses an HTTP response from a DeleteV1ProjectsProjectNameDmDevicesGuidWithResponse call
func ParseDeleteV1ProjectsProjectNameDmDevicesGuidResponse(rsp *http.Response) (*DeleteV1ProjectsProjectNameDmDevicesGuidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1ProjectsProjectNameDmDevicesGuidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 204:
		var dest DeleteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON204 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest DeleteErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetV1ProjectsProjectNameDmDevicesGuidResponse parses an HTTP response from a GetV1ProjectsProjectNameDmDevicesGuidWithResponse call
func ParseGetV1ProjectsProjectNameDmDevicesGuidResponse(rsp *http.Response) (*GetV1ProjectsProjectNameDmDevicesGuidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ProjectsProjectNameDmDevicesGuidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Device
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
