// Package mps provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package mps

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DeleteErrorResponse defines model for DeleteErrorResponse.
type DeleteErrorResponse struct {
	// Error server error message
	Error *string `json:"error,omitempty"`

	// ErrorDescription contains device guid
	ErrorDescription *string `json:"errorDescription,omitempty"`

	// Success HTTP returncode
	Success *int `json:"success,omitempty"`
}

// DeleteResponse defines model for DeleteResponse.
type DeleteResponse struct {
	// Success HTTP returncode
	Success *int `json:"success,omitempty"`
}

// Device defines model for Device.
type Device struct {
	ConnectionStatus *bool `json:"connectionStatus,omitempty"`
	DeviceInfo       *struct {
		CurrentMode *string    `json:"currentMode,omitempty"`
		Features    *string    `json:"features,omitempty"`
		FwBuild     *string    `json:"fwBuild,omitempty"`
		FwSku       *string    `json:"fwSku,omitempty"`
		FwVersion   *string    `json:"fwVersion,omitempty"`
		IpAddress   *string    `json:"ipAddress,omitempty"`
		LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	} `json:"deviceInfo,omitempty"`
	DnsSuffix        *string    `json:"dnsSuffix,omitempty"`
	FriendlyName     *string    `json:"friendlyName,omitempty"`
	Guid             *string    `json:"guid,omitempty"`
	Hostname         *string    `json:"hostname,omitempty"`
	LastConnected    *time.Time `json:"lastConnected,omitempty"`
	LastDisconnected *time.Time `json:"lastDisconnected,omitempty"`
	LastSeen         *time.Time `json:"lastSeen,omitempty"`
	MpsInstance      *string    `json:"mpsInstance,omitempty"`
	Mpsusername      *string    `json:"mpsusername,omitempty"`
	Tags             *[]string  `json:"tags,omitempty"`
	Tenantid         *string    `json:"tenantid,omitempty"`
}

// GeneralSettingsResponse defines model for GeneralSettingsResponse.
type GeneralSettingsResponse struct {
	Body *struct {
		AMTNetworkEnabled             *int    `json:"AMTNetworkEnabled,omitempty"`
		DDNSPeriodicUpdateInterval    *int    `json:"DDNSPeriodicUpdateInterval,omitempty"`
		DDNSTTL                       *int    `json:"DDNSTTL,omitempty"`
		DDNSUpdateByDHCPServerEnabled *bool   `json:"DDNSUpdateByDHCPServerEnabled,omitempty"`
		DDNSUpdateEnabled             *bool   `json:"DDNSUpdateEnabled,omitempty"`
		DHCPv6ConfigurationTimeout    *int    `json:"DHCPv6ConfigurationTimeout,omitempty"`
		DigestRealm                   *string `json:"DigestRealm,omitempty"`
		DomainName                    *string `json:"DomainName,omitempty"`
		ElementName                   *string `json:"ElementName,omitempty"`
		HostName                      *string `json:"HostName,omitempty"`
		HostOSFQDN                    *string `json:"HostOSFQDN,omitempty"`
		IdleWakeTimeout               *int    `json:"IdleWakeTimeout,omitempty"`
		InstanceID                    *string `json:"InstanceID,omitempty"`
		NetworkInterfaceEnabled       *bool   `json:"NetworkInterfaceEnabled,omitempty"`
		PingResponseEnabled           *bool   `json:"PingResponseEnabled,omitempty"`
		PowerSource                   *int    `json:"PowerSource,omitempty"`
		PreferredAddressFamily        *int    `json:"PreferredAddressFamily,omitempty"`
		PresenceNotificationInterval  *int    `json:"PresenceNotificationInterval,omitempty"`
		PrivacyLevel                  *int    `json:"PrivacyLevel,omitempty"`
		RmcpPingResponseEnabled       *bool   `json:"RmcpPingResponseEnabled,omitempty"`
		SharedFQDN                    *bool   `json:"SharedFQDN,omitempty"`
		WsmanOnlyMode                 *bool   `json:"WsmanOnlyMode,omitempty"`
	} `json:"Body,omitempty"`
	Header *struct {
		Action      *string `json:"Action,omitempty"`
		MessageID   *string `json:"MessageID,omitempty"`
		Method      *string `json:"Method,omitempty"`
		RelatesTo   *string `json:"RelatesTo,omitempty"`
		ResourceURI *string `json:"ResourceURI,omitempty"`
		To          *string `json:"To,omitempty"`
	} `json:"Header,omitempty"`
}

// DeleteV1ProjectsProjectNameDmDevicesGuidParams defines parameters for DeleteV1ProjectsProjectNameDmDevicesGuid.
type DeleteV1ProjectsProjectNameDmDevicesGuidParams struct {
	// IsSecretToBeDeleted Delete device information from both the Database **AND Secret Storage**. Caution: This will delete the stored device passwords in Secret Storage.
	IsSecretToBeDeleted *bool `form:"isSecretToBeDeleted,omitempty" json:"isSecretToBeDeleted,omitempty"`
}
