# Gitleaks config to allowlist test PKCS12 file
###############################
# Robust gitleaks allowlist for test PKCS12 file
[allowlist]
files = [
  "internal/cli/testdata/sample.pfx"
]
paths = [
  "internal/cli/testdata/sample.pfx"
]
commits = []

[[rules]]
description = "pkcs12-file"
allowlist = { paths = ["internal/cli/testdata/sample.pfx"] }
