version: "2"
run:
  build-tags:
    - codeanalysis
linters:
  enable:
    - copyloopvar
    - dogsled
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of `.*Close` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Flush` is not checked
      - path: (.+)\.go$
        text: G115.*
      - path: (.+)\.go$
        text: G101.*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
