version = 1

[[annotations]]
path = [
    ".github/PULL_REQUEST_TEMPLATE.md",
    "artifacts/**",
    "REUSE.toml",
    "go.sum",
    "VERSION",
    "**.json",
    "**.png",
    "internal/cli/deployment-mock-rest_test.go",
    "internal/cli/testdata/**",
    "docs/cli/**",
    "pkg/rest/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "ui/kvm-viewer/angular.json",
    "ui/kvm-viewer/package.json",
    "ui/kvm-viewer/package-lock.json",
    "ui/kvm-viewer/tsconfig.json",
    "ui/kvm-viewer/tsconfig.app.json",
    "ui/kvm-viewer/tsconfig.spec.json",
    "ui/kvm-viewer/public/favicon.ico",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"

