// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rest/rps/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/rest/rps/client.go -destination=pkg/rest/rps/mock_client.go -package=rps
//

// Package rps is a generated GoMock package.
package rps

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Create8021xConfig mocks base method.
func (m *MockClientInterface) Create8021xConfig(ctx context.Context, body Create8021xConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create8021xConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create8021xConfig indicates an expected call of Create8021xConfig.
func (mr *MockClientInterfaceMockRecorder) Create8021xConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create8021xConfig", reflect.TypeOf((*MockClientInterface)(nil).Create8021xConfig), varargs...)
}

// Create8021xConfigWithBody mocks base method.
func (m *MockClientInterface) Create8021xConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create8021xConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create8021xConfigWithBody indicates an expected call of Create8021xConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) Create8021xConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create8021xConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).Create8021xConfigWithBody), varargs...)
}

// CreateCIRAConfig mocks base method.
func (m *MockClientInterface) CreateCIRAConfig(ctx context.Context, body CreateCIRAConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCIRAConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCIRAConfig indicates an expected call of CreateCIRAConfig.
func (mr *MockClientInterfaceMockRecorder) CreateCIRAConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCIRAConfig", reflect.TypeOf((*MockClientInterface)(nil).CreateCIRAConfig), varargs...)
}

// CreateCIRAConfigWithBody mocks base method.
func (m *MockClientInterface) CreateCIRAConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCIRAConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCIRAConfigWithBody indicates an expected call of CreateCIRAConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateCIRAConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCIRAConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateCIRAConfigWithBody), varargs...)
}

// CreateDomain mocks base method.
func (m *MockClientInterface) CreateDomain(ctx context.Context, body CreateDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDomain", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomain indicates an expected call of CreateDomain.
func (mr *MockClientInterfaceMockRecorder) CreateDomain(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomain", reflect.TypeOf((*MockClientInterface)(nil).CreateDomain), varargs...)
}

// CreateDomainWithBody mocks base method.
func (m *MockClientInterface) CreateDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDomainWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomainWithBody indicates an expected call of CreateDomainWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateDomainWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomainWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateDomainWithBody), varargs...)
}

// CreateProfile mocks base method.
func (m *MockClientInterface) CreateProfile(ctx context.Context, body CreateProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProfile", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockClientInterfaceMockRecorder) CreateProfile(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockClientInterface)(nil).CreateProfile), varargs...)
}

// CreateProfileWithBody mocks base method.
func (m *MockClientInterface) CreateProfileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProfileWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfileWithBody indicates an expected call of CreateProfileWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateProfileWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfileWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateProfileWithBody), varargs...)
}

// CreateWirelessConfig mocks base method.
func (m *MockClientInterface) CreateWirelessConfig(ctx context.Context, body CreateWirelessConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWirelessConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWirelessConfig indicates an expected call of CreateWirelessConfig.
func (mr *MockClientInterfaceMockRecorder) CreateWirelessConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWirelessConfig", reflect.TypeOf((*MockClientInterface)(nil).CreateWirelessConfig), varargs...)
}

// CreateWirelessConfigWithBody mocks base method.
func (m *MockClientInterface) CreateWirelessConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWirelessConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWirelessConfigWithBody indicates an expected call of CreateWirelessConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateWirelessConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWirelessConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).CreateWirelessConfigWithBody), varargs...)
}

// Edit8021xConfig mocks base method.
func (m *MockClientInterface) Edit8021xConfig(ctx context.Context, body Edit8021xConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Edit8021xConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit8021xConfig indicates an expected call of Edit8021xConfig.
func (mr *MockClientInterfaceMockRecorder) Edit8021xConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit8021xConfig", reflect.TypeOf((*MockClientInterface)(nil).Edit8021xConfig), varargs...)
}

// Edit8021xConfigWithBody mocks base method.
func (m *MockClientInterface) Edit8021xConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Edit8021xConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit8021xConfigWithBody indicates an expected call of Edit8021xConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) Edit8021xConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit8021xConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).Edit8021xConfigWithBody), varargs...)
}

// EditCIRAConfig mocks base method.
func (m *MockClientInterface) EditCIRAConfig(ctx context.Context, body EditCIRAConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditCIRAConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCIRAConfig indicates an expected call of EditCIRAConfig.
func (mr *MockClientInterfaceMockRecorder) EditCIRAConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCIRAConfig", reflect.TypeOf((*MockClientInterface)(nil).EditCIRAConfig), varargs...)
}

// EditCIRAConfigWithBody mocks base method.
func (m *MockClientInterface) EditCIRAConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditCIRAConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCIRAConfigWithBody indicates an expected call of EditCIRAConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) EditCIRAConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCIRAConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).EditCIRAConfigWithBody), varargs...)
}

// EditWirelessConfig mocks base method.
func (m *MockClientInterface) EditWirelessConfig(ctx context.Context, body EditWirelessConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditWirelessConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditWirelessConfig indicates an expected call of EditWirelessConfig.
func (mr *MockClientInterfaceMockRecorder) EditWirelessConfig(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditWirelessConfig", reflect.TypeOf((*MockClientInterface)(nil).EditWirelessConfig), varargs...)
}

// EditWirelessConfigWithBody mocks base method.
func (m *MockClientInterface) EditWirelessConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditWirelessConfigWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditWirelessConfigWithBody indicates an expected call of EditWirelessConfigWithBody.
func (mr *MockClientInterfaceMockRecorder) EditWirelessConfigWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditWirelessConfigWithBody", reflect.TypeOf((*MockClientInterface)(nil).EditWirelessConfigWithBody), varargs...)
}

// Get8021xConfig mocks base method.
func (m *MockClientInterface) Get8021xConfig(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get8021xConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get8021xConfig indicates an expected call of Get8021xConfig.
func (mr *MockClientInterfaceMockRecorder) Get8021xConfig(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get8021xConfig", reflect.TypeOf((*MockClientInterface)(nil).Get8021xConfig), varargs...)
}

// GetAll8021xConfigs mocks base method.
func (m *MockClientInterface) GetAll8021xConfigs(ctx context.Context, params *GetAll8021xConfigsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll8021xConfigs", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll8021xConfigs indicates an expected call of GetAll8021xConfigs.
func (mr *MockClientInterfaceMockRecorder) GetAll8021xConfigs(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll8021xConfigs", reflect.TypeOf((*MockClientInterface)(nil).GetAll8021xConfigs), varargs...)
}

// GetAllCIRAConfigs mocks base method.
func (m *MockClientInterface) GetAllCIRAConfigs(ctx context.Context, params *GetAllCIRAConfigsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllCIRAConfigs", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCIRAConfigs indicates an expected call of GetAllCIRAConfigs.
func (mr *MockClientInterfaceMockRecorder) GetAllCIRAConfigs(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCIRAConfigs", reflect.TypeOf((*MockClientInterface)(nil).GetAllCIRAConfigs), varargs...)
}

// GetAllDomains mocks base method.
func (m *MockClientInterface) GetAllDomains(ctx context.Context, params *GetAllDomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllDomains", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDomains indicates an expected call of GetAllDomains.
func (mr *MockClientInterfaceMockRecorder) GetAllDomains(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDomains", reflect.TypeOf((*MockClientInterface)(nil).GetAllDomains), varargs...)
}

// GetAllProfiles mocks base method.
func (m *MockClientInterface) GetAllProfiles(ctx context.Context, params *GetAllProfilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllProfiles", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProfiles indicates an expected call of GetAllProfiles.
func (mr *MockClientInterfaceMockRecorder) GetAllProfiles(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProfiles", reflect.TypeOf((*MockClientInterface)(nil).GetAllProfiles), varargs...)
}

// GetAllWirelessConfigs mocks base method.
func (m *MockClientInterface) GetAllWirelessConfigs(ctx context.Context, params *GetAllWirelessConfigsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllWirelessConfigs", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWirelessConfigs indicates an expected call of GetAllWirelessConfigs.
func (mr *MockClientInterfaceMockRecorder) GetAllWirelessConfigs(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWirelessConfigs", reflect.TypeOf((*MockClientInterface)(nil).GetAllWirelessConfigs), varargs...)
}

// GetApiV1AdminHealth mocks base method.
func (m *MockClientInterface) GetApiV1AdminHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1AdminHealth", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1AdminHealth indicates an expected call of GetApiV1AdminHealth.
func (mr *MockClientInterfaceMockRecorder) GetApiV1AdminHealth(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1AdminHealth", reflect.TypeOf((*MockClientInterface)(nil).GetApiV1AdminHealth), varargs...)
}

// GetCIRAConfig mocks base method.
func (m *MockClientInterface) GetCIRAConfig(ctx context.Context, configName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, configName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCIRAConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIRAConfig indicates an expected call of GetCIRAConfig.
func (mr *MockClientInterfaceMockRecorder) GetCIRAConfig(ctx, configName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, configName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIRAConfig", reflect.TypeOf((*MockClientInterface)(nil).GetCIRAConfig), varargs...)
}

// GetDomain mocks base method.
func (m *MockClientInterface) GetDomain(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDomain", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockClientInterfaceMockRecorder) GetDomain(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockClientInterface)(nil).GetDomain), varargs...)
}

// GetProfile mocks base method.
func (m *MockClientInterface) GetProfile(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProfile", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockClientInterfaceMockRecorder) GetProfile(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockClientInterface)(nil).GetProfile), varargs...)
}

// GetVersion mocks base method.
func (m *MockClientInterface) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVersion", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockClientInterfaceMockRecorder) GetVersion(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockClientInterface)(nil).GetVersion), varargs...)
}

// GetWirelessConfig mocks base method.
func (m *MockClientInterface) GetWirelessConfig(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWirelessConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWirelessConfig indicates an expected call of GetWirelessConfig.
func (mr *MockClientInterfaceMockRecorder) GetWirelessConfig(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWirelessConfig", reflect.TypeOf((*MockClientInterface)(nil).GetWirelessConfig), varargs...)
}

// Remove8021xConfig mocks base method.
func (m *MockClientInterface) Remove8021xConfig(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Remove8021xConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove8021xConfig indicates an expected call of Remove8021xConfig.
func (mr *MockClientInterfaceMockRecorder) Remove8021xConfig(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove8021xConfig", reflect.TypeOf((*MockClientInterface)(nil).Remove8021xConfig), varargs...)
}

// RemoveCIRAConfig mocks base method.
func (m *MockClientInterface) RemoveCIRAConfig(ctx context.Context, configName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, configName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveCIRAConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCIRAConfig indicates an expected call of RemoveCIRAConfig.
func (mr *MockClientInterfaceMockRecorder) RemoveCIRAConfig(ctx, configName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, configName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCIRAConfig", reflect.TypeOf((*MockClientInterface)(nil).RemoveCIRAConfig), varargs...)
}

// RemoveDomain mocks base method.
func (m *MockClientInterface) RemoveDomain(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveDomain", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDomain indicates an expected call of RemoveDomain.
func (mr *MockClientInterfaceMockRecorder) RemoveDomain(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDomain", reflect.TypeOf((*MockClientInterface)(nil).RemoveDomain), varargs...)
}

// RemoveProfile mocks base method.
func (m *MockClientInterface) RemoveProfile(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveProfile", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProfile indicates an expected call of RemoveProfile.
func (mr *MockClientInterfaceMockRecorder) RemoveProfile(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProfile", reflect.TypeOf((*MockClientInterface)(nil).RemoveProfile), varargs...)
}

// RemoveWirelessConfig mocks base method.
func (m *MockClientInterface) RemoveWirelessConfig(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveWirelessConfig", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveWirelessConfig indicates an expected call of RemoveWirelessConfig.
func (mr *MockClientInterfaceMockRecorder) RemoveWirelessConfig(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWirelessConfig", reflect.TypeOf((*MockClientInterface)(nil).RemoveWirelessConfig), varargs...)
}

// UpdateDomainSuffix mocks base method.
func (m *MockClientInterface) UpdateDomainSuffix(ctx context.Context, body UpdateDomainSuffixJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDomainSuffix", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainSuffix indicates an expected call of UpdateDomainSuffix.
func (mr *MockClientInterfaceMockRecorder) UpdateDomainSuffix(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainSuffix", reflect.TypeOf((*MockClientInterface)(nil).UpdateDomainSuffix), varargs...)
}

// UpdateDomainSuffixWithBody mocks base method.
func (m *MockClientInterface) UpdateDomainSuffixWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDomainSuffixWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainSuffixWithBody indicates an expected call of UpdateDomainSuffixWithBody.
func (mr *MockClientInterfaceMockRecorder) UpdateDomainSuffixWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainSuffixWithBody", reflect.TypeOf((*MockClientInterface)(nil).UpdateDomainSuffixWithBody), varargs...)
}

// UpdateProfile mocks base method.
func (m *MockClientInterface) UpdateProfile(ctx context.Context, body UpdateProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfile", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockClientInterfaceMockRecorder) UpdateProfile(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockClientInterface)(nil).UpdateProfile), varargs...)
}

// UpdateProfileWithBody mocks base method.
func (m *MockClientInterface) UpdateProfileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfileWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileWithBody indicates an expected call of UpdateProfileWithBody.
func (mr *MockClientInterfaceMockRecorder) UpdateProfileWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileWithBody", reflect.TypeOf((*MockClientInterface)(nil).UpdateProfileWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// Create8021xConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Create8021xConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Create8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create8021xConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*Create8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create8021xConfigWithBodyWithResponse indicates an expected call of Create8021xConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Create8021xConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create8021xConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Create8021xConfigWithBodyWithResponse), varargs...)
}

// Create8021xConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Create8021xConfigWithResponse(ctx context.Context, body Create8021xConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*Create8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create8021xConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*Create8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create8021xConfigWithResponse indicates an expected call of Create8021xConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Create8021xConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create8021xConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Create8021xConfigWithResponse), varargs...)
}

// CreateCIRAConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateCIRAConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCIRAConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCIRAConfigWithBodyWithResponse indicates an expected call of CreateCIRAConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateCIRAConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCIRAConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateCIRAConfigWithBodyWithResponse), varargs...)
}

// CreateCIRAConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateCIRAConfigWithResponse(ctx context.Context, body CreateCIRAConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCIRAConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCIRAConfigWithResponse indicates an expected call of CreateCIRAConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateCIRAConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCIRAConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateCIRAConfigWithResponse), varargs...)
}

// CreateDomainWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDomainResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDomainWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateDomainResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomainWithBodyWithResponse indicates an expected call of CreateDomainWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateDomainWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomainWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateDomainWithBodyWithResponse), varargs...)
}

// CreateDomainWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateDomainWithResponse(ctx context.Context, body CreateDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDomainResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDomainWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateDomainResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomainWithResponse indicates an expected call of CreateDomainWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateDomainWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomainWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateDomainWithResponse), varargs...)
}

// CreateProfileWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateProfileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProfileWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfileWithBodyWithResponse indicates an expected call of CreateProfileWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateProfileWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfileWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateProfileWithBodyWithResponse), varargs...)
}

// CreateProfileWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateProfileWithResponse(ctx context.Context, body CreateProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProfileWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfileWithResponse indicates an expected call of CreateProfileWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateProfileWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfileWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateProfileWithResponse), varargs...)
}

// CreateWirelessConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateWirelessConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWirelessConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWirelessConfigWithBodyWithResponse indicates an expected call of CreateWirelessConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateWirelessConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWirelessConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateWirelessConfigWithBodyWithResponse), varargs...)
}

// CreateWirelessConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateWirelessConfigWithResponse(ctx context.Context, body CreateWirelessConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWirelessConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWirelessConfigWithResponse indicates an expected call of CreateWirelessConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateWirelessConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWirelessConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CreateWirelessConfigWithResponse), varargs...)
}

// Edit8021xConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Edit8021xConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Edit8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Edit8021xConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*Edit8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit8021xConfigWithBodyWithResponse indicates an expected call of Edit8021xConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Edit8021xConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit8021xConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Edit8021xConfigWithBodyWithResponse), varargs...)
}

// Edit8021xConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Edit8021xConfigWithResponse(ctx context.Context, body Edit8021xConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*Edit8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Edit8021xConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*Edit8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit8021xConfigWithResponse indicates an expected call of Edit8021xConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Edit8021xConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit8021xConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Edit8021xConfigWithResponse), varargs...)
}

// EditCIRAConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) EditCIRAConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditCIRAConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*EditCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCIRAConfigWithBodyWithResponse indicates an expected call of EditCIRAConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) EditCIRAConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCIRAConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).EditCIRAConfigWithBodyWithResponse), varargs...)
}

// EditCIRAConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) EditCIRAConfigWithResponse(ctx context.Context, body EditCIRAConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*EditCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditCIRAConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*EditCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCIRAConfigWithResponse indicates an expected call of EditCIRAConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) EditCIRAConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCIRAConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).EditCIRAConfigWithResponse), varargs...)
}

// EditWirelessConfigWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) EditWirelessConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditWirelessConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*EditWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditWirelessConfigWithBodyWithResponse indicates an expected call of EditWirelessConfigWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) EditWirelessConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditWirelessConfigWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).EditWirelessConfigWithBodyWithResponse), varargs...)
}

// EditWirelessConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) EditWirelessConfigWithResponse(ctx context.Context, body EditWirelessConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*EditWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditWirelessConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*EditWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditWirelessConfigWithResponse indicates an expected call of EditWirelessConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) EditWirelessConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditWirelessConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).EditWirelessConfigWithResponse), varargs...)
}

// Get8021xConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Get8021xConfigWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*Get8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get8021xConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*Get8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get8021xConfigWithResponse indicates an expected call of Get8021xConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Get8021xConfigWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get8021xConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Get8021xConfigWithResponse), varargs...)
}

// GetAll8021xConfigsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetAll8021xConfigsWithResponse(ctx context.Context, params *GetAll8021xConfigsParams, reqEditors ...RequestEditorFn) (*GetAll8021xConfigsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll8021xConfigsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetAll8021xConfigsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll8021xConfigsWithResponse indicates an expected call of GetAll8021xConfigsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetAll8021xConfigsWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll8021xConfigsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetAll8021xConfigsWithResponse), varargs...)
}

// GetAllCIRAConfigsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetAllCIRAConfigsWithResponse(ctx context.Context, params *GetAllCIRAConfigsParams, reqEditors ...RequestEditorFn) (*GetAllCIRAConfigsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllCIRAConfigsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetAllCIRAConfigsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCIRAConfigsWithResponse indicates an expected call of GetAllCIRAConfigsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetAllCIRAConfigsWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCIRAConfigsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetAllCIRAConfigsWithResponse), varargs...)
}

// GetAllDomainsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetAllDomainsWithResponse(ctx context.Context, params *GetAllDomainsParams, reqEditors ...RequestEditorFn) (*GetAllDomainsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllDomainsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetAllDomainsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDomainsWithResponse indicates an expected call of GetAllDomainsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetAllDomainsWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDomainsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetAllDomainsWithResponse), varargs...)
}

// GetAllProfilesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetAllProfilesWithResponse(ctx context.Context, params *GetAllProfilesParams, reqEditors ...RequestEditorFn) (*GetAllProfilesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllProfilesWithResponse", varargs...)
	ret0, _ := ret[0].(*GetAllProfilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProfilesWithResponse indicates an expected call of GetAllProfilesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetAllProfilesWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProfilesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetAllProfilesWithResponse), varargs...)
}

// GetAllWirelessConfigsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetAllWirelessConfigsWithResponse(ctx context.Context, params *GetAllWirelessConfigsParams, reqEditors ...RequestEditorFn) (*GetAllWirelessConfigsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllWirelessConfigsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetAllWirelessConfigsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWirelessConfigsWithResponse indicates an expected call of GetAllWirelessConfigsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetAllWirelessConfigsWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWirelessConfigsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetAllWirelessConfigsWithResponse), varargs...)
}

// GetApiV1AdminHealthWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetApiV1AdminHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1AdminHealthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetApiV1AdminHealthWithResponse", varargs...)
	ret0, _ := ret[0].(*GetApiV1AdminHealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiV1AdminHealthWithResponse indicates an expected call of GetApiV1AdminHealthWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetApiV1AdminHealthWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiV1AdminHealthWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetApiV1AdminHealthWithResponse), varargs...)
}

// GetCIRAConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetCIRAConfigWithResponse(ctx context.Context, configName string, reqEditors ...RequestEditorFn) (*GetCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, configName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCIRAConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*GetCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIRAConfigWithResponse indicates an expected call of GetCIRAConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetCIRAConfigWithResponse(ctx, configName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, configName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIRAConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetCIRAConfigWithResponse), varargs...)
}

// GetDomainWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetDomainWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*GetDomainResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDomainWithResponse", varargs...)
	ret0, _ := ret[0].(*GetDomainResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomainWithResponse indicates an expected call of GetDomainWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetDomainWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetDomainWithResponse), varargs...)
}

// GetProfileWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetProfileWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*GetProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProfileWithResponse", varargs...)
	ret0, _ := ret[0].(*GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileWithResponse indicates an expected call of GetProfileWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetProfileWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetProfileWithResponse), varargs...)
}

// GetVersionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVersionWithResponse", varargs...)
	ret0, _ := ret[0].(*GetVersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionWithResponse indicates an expected call of GetVersionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetVersionWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetVersionWithResponse), varargs...)
}

// GetWirelessConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) GetWirelessConfigWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*GetWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWirelessConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*GetWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWirelessConfigWithResponse indicates an expected call of GetWirelessConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) GetWirelessConfigWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWirelessConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).GetWirelessConfigWithResponse), varargs...)
}

// Remove8021xConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) Remove8021xConfigWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*Remove8021xConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Remove8021xConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*Remove8021xConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove8021xConfigWithResponse indicates an expected call of Remove8021xConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) Remove8021xConfigWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove8021xConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).Remove8021xConfigWithResponse), varargs...)
}

// RemoveCIRAConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RemoveCIRAConfigWithResponse(ctx context.Context, configName string, reqEditors ...RequestEditorFn) (*RemoveCIRAConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, configName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveCIRAConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*RemoveCIRAConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCIRAConfigWithResponse indicates an expected call of RemoveCIRAConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RemoveCIRAConfigWithResponse(ctx, configName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, configName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCIRAConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RemoveCIRAConfigWithResponse), varargs...)
}

// RemoveDomainWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RemoveDomainWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*RemoveDomainResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveDomainWithResponse", varargs...)
	ret0, _ := ret[0].(*RemoveDomainResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDomainWithResponse indicates an expected call of RemoveDomainWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RemoveDomainWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDomainWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RemoveDomainWithResponse), varargs...)
}

// RemoveProfileWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RemoveProfileWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*RemoveProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveProfileWithResponse", varargs...)
	ret0, _ := ret[0].(*RemoveProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProfileWithResponse indicates an expected call of RemoveProfileWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RemoveProfileWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProfileWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RemoveProfileWithResponse), varargs...)
}

// RemoveWirelessConfigWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) RemoveWirelessConfigWithResponse(ctx context.Context, profileName string, reqEditors ...RequestEditorFn) (*RemoveWirelessConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, profileName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveWirelessConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*RemoveWirelessConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveWirelessConfigWithResponse indicates an expected call of RemoveWirelessConfigWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) RemoveWirelessConfigWithResponse(ctx, profileName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, profileName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWirelessConfigWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).RemoveWirelessConfigWithResponse), varargs...)
}

// UpdateDomainSuffixWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdateDomainSuffixWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainSuffixResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDomainSuffixWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateDomainSuffixResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainSuffixWithBodyWithResponse indicates an expected call of UpdateDomainSuffixWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdateDomainSuffixWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainSuffixWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdateDomainSuffixWithBodyWithResponse), varargs...)
}

// UpdateDomainSuffixWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdateDomainSuffixWithResponse(ctx context.Context, body UpdateDomainSuffixJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainSuffixResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDomainSuffixWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateDomainSuffixResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainSuffixWithResponse indicates an expected call of UpdateDomainSuffixWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdateDomainSuffixWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainSuffixWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdateDomainSuffixWithResponse), varargs...)
}

// UpdateProfileWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdateProfileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfileWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileWithBodyWithResponse indicates an expected call of UpdateProfileWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdateProfileWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdateProfileWithBodyWithResponse), varargs...)
}

// UpdateProfileWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) UpdateProfileWithResponse(ctx context.Context, body UpdateProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfileWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileWithResponse indicates an expected call of UpdateProfileWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) UpdateProfileWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).UpdateProfileWithResponse), varargs...)
}
