// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/open-edge-platform/cli/pkg/auth"
	"github.com/open-edge-platform/cli/pkg/rest/infra"
	"github.com/open-edge-platform/cli/pkg/rest/rps"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

const listAmtProfileExamples = `
// # List all sites
// orch-cli list site --project some-project

// # List all sites within specific parent region ID
// orch-cli list site --project some-project --region region-aaaa1111"
`

const getAmtProfileExamples = `
// # Get specific site information
// orch-cli get site site-aaaa1111 --project some-project
`

const createAmtProfileExamples = `
// # Create specific site

// # Create a site in a region (default longitude and latitude set to 0)
// orch-cli create site name --project some-project --region region-bbbb1111

// # Create a site in a region (default longitude and latitude set to 0)
// orch-cli create site name --project some-project --region region-bbbb1111 --longitude 5 --latitude 5
`
const deleteAmtProfileExamples = `
// # Delete specific site
// orch-cli delete site region-aaaa1111 --project some-project
`

func getListAmtProfileCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "amtprofile [flags]",
		Short:   "List all amptprofiles",
		Example: listAmtProfileExamples,
		RunE:    runListAmtProfileCommand,
	}
	//cmd.PersistentFlags().StringP("region", "r", viper.GetString("region"), "Optional filter provided as part of site list to filter sites by parent region")
	return cmd
}

func getGetAmtProfileCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "amtprofile <resourceid> [flags]",
		Short:   "Get an AMT profile",
		Example: getAmtProfileExamples,
		Args:    cobra.ExactArgs(1),
		RunE:    runGetAmtProfileCommand,
	}
	return cmd
}

func getCreateAmtProfileCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "amtprofile name [flags]",
		Short:   "Create an AMT profile",
		Example: createAmtProfileExamples,
		Args:    cobra.ExactArgs(1),
		RunE:    runCreateAmtProfileCommand,
	}
	cmd.PersistentFlags().StringP("domain-suffix", "d", viper.GetString("domain-suffix"), "Mandatory domain name suffix")
	cmd.PersistentFlags().StringP("cert", "c", viper.GetString("cert"), "Mandatory path to SSL certificate")
	cmd.PersistentFlags().StringP("cert-pass", "s", viper.GetString("cert-pass"), "Mandatory password for SSL certificate")
	cmd.PersistentFlags().StringP("cert-format", "f", viper.GetString("cert-format"), "Mandatory format of SSL certificate")

	return cmd
}

func getDeleteAmtProfileCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "amtprofile <resourceid> [flags]",
		Short:   "Delete an AMT profile",
		Example: deleteAmtProfileExamples,
		Args:    cobra.ExactArgs(1),
		RunE:    runDeleteAmtProfileCommand,
	}
	return cmd
}

// Lists all AMT profiles
func runListAmtProfileCommand(cmd *cobra.Command, _ []string) error {
	writer, verbose := getOutputContext(cmd)
	count := true
	ctx, rpsClient, projectName, err := getRpsServiceContext(cmd)
	if err != nil {
		return err
	}

	resp, err := rpsClient.GetAllDomainsWithResponse(ctx, projectName, &rps.GetAllDomainsParams{
		Count: &count,
	}, auth.AddAuthHeader)
	if err != nil {
		return processError(err)
	}

	if err := checkResponse(resp.HTTPResponse, "error while retrieving AMT profiles"); err != nil {
		return err
	}

	var countDomainResponse rps.CountDomainResponse

	// Unmarshal the JSON data into the CountDomainResponse struct
	//The autogenerated struct in rps struct has union field with lower case and causes trouble to access externaly
	err = json.Unmarshal(resp.Body, &countDomainResponse)
	if err != nil {
		fmt.Println("Error unmarshalling JSON:", err)
		return err
	}

	printAmtProfiles(writer, countDomainResponse, verbose)

	return writer.Flush()
}

func runCreateAmtProfileCommand(cmd *cobra.Command, args []string) error {
	name := args[0]
	certpath, _ := cmd.Flags().GetString("cert")
	certpass, _ := cmd.Flags().GetString("cert-pass")
	certformat, _ := cmd.Flags().GetString("cert-format")
	domainsuffix, _ := cmd.Flags().GetString("domain-suffix")

	cert, err := readCert(certpath)
	if err != nil {
		return err
	}

	if certpass == "" {
		return errors.New("certificate passoword must be provided with --cert-pass flag ")
	}
	if certformat == "" {
		return errors.New("certificate format must be provided with --cert-format flag ")
	}
	if domainsuffix == "" {
		return errors.New("domain suffix format must be provided with --domain-suffix flag ")
	}

	ctx, rpsClient, projectName, err := getRpsServiceContext(cmd)
	if err != nil {
		return err
	}

	resp, err := rpsClient.CreateDomainWithResponse(ctx, projectName,
		rps.CreateDomainJSONRequestBody{
			DomainSuffix:                  domainsuffix,
			ProfileName:                   name,
			ProvisioningCert:              cert,
			ProvisioningCertPassword:      certpass,
			ProvisioningCertStorageFormat: certformat,
		}, auth.AddAuthHeader)
	if err != nil {
		return processError(err)
	}
	return checkResponse(resp.HTTPResponse, "error while creating AMT")
}

func runGetAmtProfileCommand(cmd *cobra.Command, args []string) error {
	// writer, verbose := getOutputContext(cmd)
	// ctx, siteClient, projectName, err := getInfraServiceContext(cmd)
	// if err != nil {
	// 	return err
	// }

	// id := args[0]

	// resp, err := siteClient.SiteServiceGetSiteWithResponse(ctx, projectName,
	// 	"empty", id, auth.AddAuthHeader)
	// if err != nil {
	// 	return processError(err)
	// }

	// if proceed, err := processResponse(resp.HTTPResponse, resp.Body, writer, verbose,
	// 	"", "error getting site"); !proceed {
	// 	return err
	// }

	// printSite(writer, resp.JSON200)
	//return writer.Flush()
	return nil
}

func runDeleteAmtProfileCommand(cmd *cobra.Command, args []string) error {
	// id := args[0]

	// ctx, siteClient, projectName, err := getInfraServiceContext(cmd)
	// if err != nil {
	// 	return err
	// }

	// resp, err := siteClient.SiteServiceDeleteSiteWithResponse(ctx, projectName,
	// 	"empty", id, auth.AddAuthHeader)
	// if err != nil {
	// 	return processError(err)
	// }

	// err = checkResponse(resp.HTTPResponse, "error while deleting site")
	// if err != nil {
	// 	if strings.Contains(string(resp.Body), `"message":"site_resource not found"`) {
	// 		return errors.New("site does not exist")
	// 	}
	// }
	// return err
	return nil
}

func printAmtProfiles(writer io.Writer, amtprofiles rps.CountDomainResponse, verbose bool) {
	if verbose {
		fmt.Fprintf(writer, "\n%s\t%s\n", "AMT Profile Name", "Info")
	} else {
		var shortHeader = fmt.Sprintf("\n%s", "AMT Profile Name")
		fmt.Fprintf(writer, "%s\n", shortHeader)
	}
	for _, domain := range *amtprofiles.Data {

		if !verbose {
			fmt.Fprintf(writer, "%s\n", domain.ProfileName)
		} else {
			fmt.Fprintf(writer, "%s\t%s\n", domain.ProfileName, domain.DomainSuffix)
		}
	}
}

// Prints output details of site
func printAmtProfile(writer io.Writer, site *infra.SiteResource) {

	// _, _ = fmt.Fprintf(writer, "Name: \t%s\n", *site.Name)
	// _, _ = fmt.Fprintf(writer, "Resource ID: \t%s\n", *site.ResourceId)
	// _, _ = fmt.Fprintf(writer, "Region: \t%s %s\n", *site.Region.Name, *site.RegionId)
	// _, _ = fmt.Fprintf(writer, "Longtitude: \t%v\n", float64(*site.SiteLng)/10000000)
	// _, _ = fmt.Fprintf(writer, "Latitude: \t%v\n", float64(*site.SiteLat)/10000000)

}

func readCert(certPath string) ([]byte, error) {

	if certPath == "" {
		return nil, errors.New("certificate path must be provided with --cert flag ")
	}
	certData, err := os.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read certificate file: %w", err)
	}

	return certData, nil
}
