// SPDX-FileCopyrightText: (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.

package keycloak

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockClientInterface) ListUsers(ctx context.Context, realm string) ([]UserRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, realm)
	ret0, _ := ret[0].([]UserRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockClientInterfaceMockRecorder) ListUsers(ctx, realm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockClientInterface)(nil).ListUsers), ctx, realm)
}

// GetUserByUsername mocks base method.
func (m *MockClientInterface) GetUserByUsername(ctx context.Context, realm, username string) (*UserRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, realm, username)
	ret0, _ := ret[0].(*UserRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockClientInterfaceMockRecorder) GetUserByUsername(ctx, realm, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockClientInterface)(nil).GetUserByUsername), ctx, realm, username)
}

// GetUser mocks base method.
func (m *MockClientInterface) GetUser(ctx context.Context, realm, userID string) (*UserRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, realm, userID)
	ret0, _ := ret[0].(*UserRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientInterfaceMockRecorder) GetUser(ctx, realm, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClientInterface)(nil).GetUser), ctx, realm, userID)
}

// CreateUser mocks base method.
func (m *MockClientInterface) CreateUser(ctx context.Context, realm string, user UserRepresentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, realm, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientInterfaceMockRecorder) CreateUser(ctx, realm, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClientInterface)(nil).CreateUser), ctx, realm, user)
}

// DeleteUser mocks base method.
func (m *MockClientInterface) DeleteUser(ctx context.Context, realm, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, realm, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockClientInterfaceMockRecorder) DeleteUser(ctx, realm, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockClientInterface)(nil).DeleteUser), ctx, realm, userID)
}

// SetPassword mocks base method.
func (m *MockClientInterface) SetPassword(ctx context.Context, realm, userID, password string, temporary bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, realm, userID, password, temporary)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockClientInterfaceMockRecorder) SetPassword(ctx, realm, userID, password, temporary interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockClientInterface)(nil).SetPassword), ctx, realm, userID, password, temporary)
}

// ListUserGroups mocks base method.
func (m *MockClientInterface) ListUserGroups(ctx context.Context, realm, userID string) ([]GroupRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserGroups", ctx, realm, userID)
	ret0, _ := ret[0].([]GroupRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserGroups indicates an expected call of ListUserGroups.
func (mr *MockClientInterfaceMockRecorder) ListUserGroups(ctx, realm, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserGroups", reflect.TypeOf((*MockClientInterface)(nil).ListUserGroups), ctx, realm, userID)
}

// AddUserToGroup mocks base method.
func (m *MockClientInterface) AddUserToGroup(ctx context.Context, realm, userID, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, realm, userID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockClientInterfaceMockRecorder) AddUserToGroup(ctx, realm, userID, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockClientInterface)(nil).AddUserToGroup), ctx, realm, userID, groupID)
}

// RemoveUserFromGroup mocks base method.
func (m *MockClientInterface) RemoveUserFromGroup(ctx context.Context, realm, userID, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, realm, userID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockClientInterfaceMockRecorder) RemoveUserFromGroup(ctx, realm, userID, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockClientInterface)(nil).RemoveUserFromGroup), ctx, realm, userID, groupID)
}

// ListGroups mocks base method.
func (m *MockClientInterface) ListGroups(ctx context.Context, realm string) ([]GroupRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx, realm)
	ret0, _ := ret[0].([]GroupRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockClientInterfaceMockRecorder) ListGroups(ctx, realm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockClientInterface)(nil).ListGroups), ctx, realm)
}
